sdd

diff --git a/.github/workflows/3.yml b/.github/workflows/3.yml
--- a/.github/workflows/3.yml
+++ b/.github/workflows/3.yml
@@ -1,35 +1,35 @@
-name: Run job if any dependency succeeds
-on:
-  push:
-    branches: [ dev ]
-jobs:
-  dep1:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Run FAILING script
-        run: exit 1 
-  dep2:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Run SUCCESS script
-        run: exit 1
-  job:
-    runs-on: ubuntu-latest
-    if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
-    needs: [dep1, dep2]
-    steps:
-      - name: Hello World        
-        env:
-          NEEDS: ${{ toJSON(needs) }}     
-        run: |
-          echo "$NEEDS"
-  nextjob:
-    runs-on: ubuntu-latest
-    if: ${{ always() }}
-    needs: [job]
-    steps:
-      - name: Hello World        
-        env:
-          NEEDS: ${{ toJSON(needs) }}     
-        run: |
-          echo "$NEEDS"
+# name: Run job if any dependency succeeds
+# on:
+#   push:
+#     branches: [ dev ]
+# jobs:
+#   dep1:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Run FAILING script
+#         run: exit 1 
+#   dep2:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Run SUCCESS script
+#         run: exit 1
+#   job:
+#     runs-on: ubuntu-latest
+#     if: ${{ always() && contains(join(needs.*.result, ','), 'failure') }}
+#     needs: [dep1, dep2]
+#     steps:
+#       - name: Hello World        
+#         env:
+#           NEEDS: ${{ toJSON(needs) }}     
+#         run: |
+#           echo "$NEEDS"
+#   nextjob:
+#     runs-on: ubuntu-latest
+#     if: ${{ always() }}
+#     needs: [job]
+#     steps:
+#       - name: Hello World        
+#         env:
+#           NEEDS: ${{ toJSON(needs) }}     
+#         run: |
+#           echo "$NEEDS"
