ERSrdtrfiytswgb

diff --git a/.github/workflows/folder.yml b/.github/workflows/folder.yml
--- a/.github/workflows/folder.yml
+++ b/.github/workflows/folder.yml
@@ -55,18 +55,14 @@ jobs:
           for file_name in "${unique_file_names[@]}"; do
                 if [[ ! " ${file_names_to_ignore[*]} " =~ " ${changedfiles[i]##*/} " ]]; then
                       exit 0
-                else
-                    if [[ ! "${file_name}" =~ [0-9]{4}_[A-Z0-9_]*.[a-zA-Z]*$ ]]; then
-                        invalid_file_names+=(${file_name})
-                        echo ${file_name}
-                        echo "Invalid FileName" 
-                        exit 1
-                    fi
-              fi
-             
-
-
-          done 
+                fi
+                if [[ ! "${file_name}" =~ [0-9]{4}_[A-Z0-9_]*.[a-zA-Z]*$ ]]; then
+                    invalid_file_names+=(${file_name})
+                    echo ${file_name}
+                    echo "Invalid FileName" 
+                    exit 1
+                fi
+            done 
 
           if [[ ! -z "$invalid_dirs" || ! -z "$invalid_file_names" ]]; 
               then
