ERSrdtrfiytswgb

diff --git a/.github/workflows/folder.yml b/.github/workflows/folder.yml
--- a/.github/workflows/folder.yml
+++ b/.github/workflows/folder.yml
@@ -50,13 +50,18 @@ jobs:
           for dir in "${unique_dirs[@]}"; do
               if [[ ! "${dir}" =~ ^[A-Z0-9._]*$ ]]; then
                   invalid_dirs+=(${dir}) 
+                  echo "Invalid Dirrectory Name"
+                  exit 1
               fi
           done
 
+          
           invalid_file_names=()
           for file_name in "${unique_file_names[@]}"; do
               if [[ ! "${file_name}" =~ [0-9]{4}_[A-Z0-9_]*.[a-zA-Z]*$ ]]; then
-                  invalid_file_names+=(${file_name}) 
+                  invalid_file_names+=(${file_name})
+                  echo "Invalid FileName"
+                  exit 1
               fi
           done
 
@@ -64,12 +69,12 @@ jobs:
               then
                   echo "Failed!!"
                   if [[ ! -z "$invalid_dirs" ]]; then
-                      echo "Invalid Directory Names"
                       echo "${invalid_dirs[@]}"
+                      exit 1
                   fi 
                   if [[ ! -z "$invalid_file_names" ]]; then
-                      echo "Invalid File Names"
                       echo "${invalid_file_names[@]}"
+                      exit 1
                   fi
               else
                   echo "Success!!"
