ERSrdtrfiytswgb

diff --git a/.github/workflows/folder.yml b/.github/workflows/folder.yml
--- a/.github/workflows/folder.yml
+++ b/.github/workflows/folder.yml
@@ -44,15 +44,27 @@ jobs:
           invalid_dirs=()
           for dir in "${unique_dirs[@]}"; do
               if [[ ! "${dir}" =~ ^[A-Z0-9._]*$ ]]; then
-                    echo ${dir}
                   invalid_dirs+=(${dir}) 
-                  
+                  echo ${dir}
                   echo "Invalid Dirrectory Name"
                   exit 1
               fi
           done  
 
-          
+          invalid_file_names=()
+          for file_name in "${unique_file_names[@]}"; do
+              if [[ ! " ${file_names_to_ignore[*]} " =~ " ${changedfiles[i]##*/} " ]]; then
+                    exit 0                           
+              fi
+              if [[ ! "${file_name}" =~ [0-9]{4}_[A-Z0-9_]*.[a-zA-Z]*$ ]]; then
+                    invalid_file_names+=(${file_name})
+                    echo ${file_name}
+                    echo "Invalid FileName" 
+                    exit 1
+              fi
+            
+          done 
+
           if [[ ! -z "$invalid_dirs" || ! -z "$invalid_file_names" ]]; 
               then
                   echo "Failed!!"
