ERSrdtrfiytswgb

diff --git a/.github/workflows/folder.yml b/.github/workflows/folder.yml
--- a/.github/workflows/folder.yml
+++ b/.github/workflows/folder.yml
@@ -27,38 +27,39 @@ jobs:
                   unset 'changedfiles[i]'
                   echo "${changedfiles[i]}"
               fi
-          done
-          unique_dirs=()
-          unique_file_names=()
-          for i in "${!changedfiles[@]}"; do
-              if [[ ! " ${file_names_to_ignore[*]} " =~ " ${changedfiles[i]##*/} " ]]; then
-                  unique_file_names+=(${changedfiles[i]##*/})
-              fi
-              IFS='/' read -ra path <<< "${changedfiles[i]%/*}/"
-              for i in "${path[@]}"; do
-                  if [[ ! " ${unique_dirs[*]} " =~ " ${i} " ]]; then
-                      unique_dirs+=(${i})
-                  fi
-              done
-          done
-          invalid_dirs=()
-          for dir in "${unique_dirs[@]}"; do
-              if [[ ! "${dir}" =~ ^[A-Z0-9._]*$ ]]; then
-                  invalid_dirs+=(${dir}) 
-                  echo ${dir}
-                  echo "Invalid Dirrectory Name"
+
+            unique_dirs=()
+            unique_file_names=()
+            for i in "${!changedfiles[@]}"; do
+                if [[ ! " ${file_names_to_ignore[*]} " =~ " ${changedfiles[i]##*/} " ]]; then
+                    unique_file_names+=(${changedfiles[i]##*/})
+                fi
+                IFS='/' read -ra path <<< "${changedfiles[i]%/*}/"
+                for i in "${path[@]}"; do
+                    if [[ ! " ${unique_dirs[*]} " =~ " ${i} " ]]; then
+                        unique_dirs+=(${i})
+                    fi
+                done
+            done
+            invalid_dirs=()
+            for dir in "${unique_dirs[@]}"; do
+                if [[ ! "${dir}" =~ ^[A-Z0-9._]*$ ]]; then
+                    invalid_dirs+=(${dir}) 
+                    echo ${dir}
+                    echo "Invalid Dirrectory Name"
+                    exit 1
+                fi
+            done   
+            invalid_file_names=()
+            for file_name in "${unique_file_names[@]}"; do
+              if [[ ! "${file_name}" =~ [0-9]{4}_[A-Z0-9_]*.[a-zA-Z]*$ ]]; then
+                  invalid_file_names+=(${file_name})
+                  echo ${file_name}
+                  echo "Invalid FileName" 
                   exit 1
               fi
-          done   
-          invalid_file_names=()
-          for file_name in "${unique_file_names[@]}"; do
-            if [[ ! "${file_name}" =~ [0-9]{4}_[A-Z0-9_]*.[a-zA-Z]*$ ]]; then
-                invalid_file_names+=(${file_name})
-                echo ${file_name}
-                echo "Invalid FileName" 
-                exit 1
-            fi
-          done 
+            done 
+          done
         # Define step output named pyfiles base on git diff command to find comma saperated relative paths of commited python files
       
       # - name: Print files to be validated
